In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("../../data/original/Cu-NLP/CU-NLP.csv", sep=";", encoding="cp857")

In [8]:
df.head(10)

,no,question1,question2,grade
0,0,"If the question is IR-Based, I will do the fol...",Using semantic analysis methods. We can use ve...,25
1,1,"If the question is IR-Based, I will do the fol...","we should use vector space model. firstly, bin...",25
2,2,"If the question is IR-Based, I will do the fol...","Assume we have a question like "" Why the sky i...",50
3,3,"If the question is IR-Based, I will do the fol...",We can use Vector Space Model that is represen...,25
4,4,"If the question is IR-Based, I will do the fol...",In this corpus we will use sentence segmenting...,50
5,5,"If the question is IR-Based, I will do the fol...","For example , Where do you live ? First step->...",25
6,6,"If the question is IR-Based, I will do the fol...",I will choose keywords in question sentence. A...,25
7,7,"If the question is IR-Based, I will do the fol...",I can find with corperoble (karşılaştırlabilir...,0
8,8,"If the question is IR-Based, I will do the fol...",We take the words as key in the short question...,25
9,9,"If the question is Knowledge-Based, I will do ...",Assume that our corpus is wordnet. We can be e...,50

In [9]:
df.describe()

               no       grade
count  171.000000  171.000000
mean    85.000000   27.953216
std     49.507575   24.486926
min      0.000000    0.000000
25%     42.500000   10.000000
50%     85.000000   25.000000
75%    127.500000   45.000000
max    170.000000  100.000000

In [10]:
df.nunique()

no           171
question1      5
question2    171
grade          9
dtype: int64